// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibnrtvrxogkksldvxici.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibnJ0dnJ4b2dra3NsZHZ4aWNpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE3NDkxMTQsImV4cCI6MjA3NzMyNTExNH0.VcedR4bpqo__fVsnrdYLc09sZVONZovtsQT4kM4r0u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});

// Listener para detectar problemas de autenticação
supabase.auth.onAuthStateChange((event, session) => {
  console.log('🔐 Supabase Auth Event:', event);

  if (event === 'SIGNED_OUT') {
    console.log('📤 Usuário deslogado do Supabase');
  } else if (event === 'SIGNED_IN') {
    console.log('📥 Usuário logado no Supabase');
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('🔄 Token Supabase renovado automaticamente');
  } else if (event === 'PASSWORD_RECOVERY') {
    console.log('🔑 Recuperação de senha iniciada');
  }

  if (!session) {
    console.log('⚠️ Sessão Supabase não encontrada');
  } else {
    console.log('✅ Sessão Supabase ativa até:', new Date(session.expires_at * 1000));
  }
});